### ISSUE TITLE
Created a Kanban board for our project

### ISSUE THREAD

**Issue by amon-cofie** [amon-cofie/DavRich-Recipe-App#11]
- We created a new project
- We created issues for each task in the project
- Created tasks for each milestone

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue, that does not have a link to your GitHub project and 
information about the number of people in  your group 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
