### ISSUE TITLE
Created a Kanban board for our project

### ISSUE THREAD

**Issue by amon-cofie** [amon-cofie/DavRich-Recipe-App#12]
- We created a new project
- We created issues for each task in the project
- Created tasks for each milestone

We are two collaborators on this project:
- @RichardChileya 
- @amon-cofie 

This is a link to our [kanban board](https://github.com/amon-cofie/DavRich-Recipe-App/projects/2)

**Comment by Whoistolu** [comment]
Hi Team,
@amon-cofie and @RichardChileya 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] A part of the project requirement states each card should have the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work. Please add this.
- [ ] [REQUIRED] It is also a core requirement that all cards are assigned to team members. A circle with each user's avatar should be on each card. Let's also fix this before asking for another review. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/58692590/218496300-a5c532bb-1430-40a9-8088-63a14989859d.png">

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GzimAsani** [comment]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA
### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
